### ISSUE TITLE
Flat fbtrex-data format

### ISSUE THREAD

**Issue by EduardoHargreaves** [tracking-exposed/experiments-data#1]
I would like to know if it is possible to remove the field "externals" from fbtrex-data and add to post-publication.
Reasons:
1)  I think that "externals" is a property more related to the the post itself than the visualization. If there is a separated structure accounting for the posts, I think "externals" should be there.
2) I work with Matlab and it is better to work with a dataset in table format. The conversion will be much faster and easier without this field.

**Comment by vecna** [comment]
@EduardoHargreaves right spot, now it is done, I've issued new files
